
<pre>
<center><b><h1>Machine Learning</b></center>

<center><b><h1>Lab - 3</b></center>    
<pre>

# 📱 Lab: Scikit-Learn Fundamentals (Google Play Store)

**Objective:** Transition from manual data cleaning to automated Machine Learning preprocessing using Scikit-Learn.

**Prerequisites:**
* Ensure you have the `googleplaystore_cleaned.csv` file (from the previous lab) in this folder.

### 1. Load Preprocessed Data
**Instruction:** Load the dataset you cleaned in the previous lab. This dataset should already have `Installs`, `Price`, and `Reviews` converted to numbers.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sln

In [3]:
df = pd.read_csv('googleplaystore_cleaned.csv')
df

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,-0.165945,19000000.0,10000.0,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,Coloring book moana,ART_AND_DESIGN,3.9,-0.165498,14000000.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,-0.117691,8700000.0,5000000.0,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,-0.046909,25000000.0,50000000.0,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,-0.165498,2800000.0,100000.0,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,-0.166008,619000.0,1000.0,Free,0.0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
6869,10834,FR Calculator,FAMILY,4.0,-0.166029,2600000.0,500.0,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
6870,10836,Sya9a Maroc - FR,FAMILY,4.5,-0.166012,53000000.0,5000.0,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
6871,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,-0.166030,3600000.0,100.0,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
6872,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,0.053995,19000000.0,10000000.0,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### Intro to Scikit-Learn
**What is Scikit-Learn?**
It is the standard library for Machine Learning in Python. We use it for:
1.  **Preprocessing:** Scaling numbers and encoding text.
2.  **Modeling:** Training algorithms.
3.  **Evaluation:** Checking accuracy.

**Task:** Import `sklearn` and check the version.

In [4]:
print(sln.__version__)

1.5.1

In [4]:
##__version__

### 3.  Train_Test_Split
**Concept:** We split data to prevent "Overfitting". The model learns from the **Train** set and is tested on the **Test** set.

**Task:** 
1. Define `X` (Features: everything except Rating/App) and `y` (Target: Rating).
2. Split the data (80% Train, 20% Test).

In [6]:
# train_test_split
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:
# --- 1. Define Features (X) and Target (y) ---
# X includes all features except 'Rating' and 'App'
X = df.drop(['Rating', 'App'], axis=1)

# y is the target variable 'Rating'
y = df['Rating']

# --- 2. Split the Data (80% Train, 20% Test) ---
# The test_size=0.2 parameter allocates 20% of the data to the test set, 
# leaving 80% for training.
# random_state ensures reproducibility of the split.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)


#Print the shapes of the resulting datasets to verify the split
print(f"Original data shape: {df.shape}")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

Original data shape: (6873, 14)
X_train shape: (5498, 12)
X_test shape: (1375, 12)
y_train shape: (5498,)
y_test shape: (1375,)

### 4. 📏 Scaling Numerical Data (StandardScaler)
**Concept:** `Installs` (Millions) are much larger than `Rating` (1-5). We scale them so the model treats them equally.

**Task:** Use `StandardScaler` on the numerical columns.

In [8]:
#StandardScaler()
#fit_transform()
from sklearn.preprocessing import StandardScaler

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("googleplaystore_cleaned.csv")   

# Select only numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("Numerical Columns:")
print(num_cols)

# Create the StandardScaler
scaler = StandardScaler()

# Scale the numeric columns 
# (fit + transform at the same time)

df[num_cols] = scaler.fit_transform(df[num_cols])

# Check the scaled data

print("\nScaled Numerical Columns (first 5 rows):")
print(df[num_cols].head(5))
print("-----------------------------------------------------------------------")
df

Numerical Columns:
Index(['Unnamed: 0', 'Rating', 'Reviews', 'Size', 'Installs', 'Price'], dtype='object')

Scaled Numerical Columns (first 5 rows):
   Unnamed: 0    Rating   Reviews      Size  Installs  Price
0   -1.774912 -0.119265 -0.165945 -0.167570 -0.175474    0.0
1   -1.774592 -0.484227 -0.165498 -0.380538 -0.165280    0.0
2   -1.774271  0.975623 -0.117691 -0.606285 -0.071661    0.0
3   -1.773950  0.610660 -0.046909  0.087992  0.864532    0.0
4   -1.773629  0.245698 -0.165498 -0.857587 -0.173602    0.0
-----------------------------------------------------------------------

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,-1.774912,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,-0.119265,-0.165945,-0.167570,-0.175474,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,-1.774592,Coloring book moana,ART_AND_DESIGN,-0.484227,-0.165498,-0.380538,-0.165280,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,-1.774271,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,0.975623,-0.117691,-0.606285,-0.071661,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,-1.773950,Sketch - Draw & Paint,ART_AND_DESIGN,0.610660,-0.046909,0.087992,0.864532,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,-1.773629,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,0.245698,-0.165498,-0.857587,-0.173602,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,1.699204,Chemin (fr),BOOKS_AND_REFERENCE,1.158104,-0.166008,-0.950484,-0.175661,Free,0.0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
6869,1.699525,FR Calculator,FAMILY,-0.301746,-0.166029,-0.866106,-0.175672,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
6870,1.700166,Sya9a Maroc - FR,FAMILY,0.610660,-0.166012,1.280615,-0.175578,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
6871,1.700487,Fr. Mike Schmitz Audio Teachings,FAMILY,1.523066,-0.166030,-0.823513,-0.175680,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
6872,1.701449,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,0.610660,0.053995,-0.167570,0.032361,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [9]:
#standardScaler()
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load your dataset
df = pd.read_csv("googleplaystore_cleaned.csv")  

# Select only numerical columns
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

print("Numerical columns to be scaled:")
print(num_cols)

# Create the scaler
scaler = StandardScaler()

# Fit and transform only numerical features
df[num_cols] = scaler.fit_transform(df[num_cols])

print("\nAfter scaling:")
print(df[num_cols].head(5))
df

Numerical columns to be scaled:
Index(['Unnamed: 0', 'Rating', 'Reviews', 'Size', 'Installs', 'Price'], dtype='object')

After scaling:
   Unnamed: 0    Rating   Reviews      Size  Installs  Price
0   -1.774912 -0.119265 -0.165945 -0.167570 -0.175474    0.0
1   -1.774592 -0.484227 -0.165498 -0.380538 -0.165280    0.0
2   -1.774271  0.975623 -0.117691 -0.606285 -0.071661    0.0
3   -1.773950  0.610660 -0.046909  0.087992  0.864532    0.0
4   -1.773629  0.245698 -0.165498 -0.857587 -0.173602    0.0

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,-1.774912,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,-0.119265,-0.165945,-0.167570,-0.175474,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,-1.774592,Coloring book moana,ART_AND_DESIGN,-0.484227,-0.165498,-0.380538,-0.165280,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,-1.774271,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,0.975623,-0.117691,-0.606285,-0.071661,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,-1.773950,Sketch - Draw & Paint,ART_AND_DESIGN,0.610660,-0.046909,0.087992,0.864532,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,-1.773629,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,0.245698,-0.165498,-0.857587,-0.173602,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6868,1.699204,Chemin (fr),BOOKS_AND_REFERENCE,1.158104,-0.166008,-0.950484,-0.175661,Free,0.0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
6869,1.699525,FR Calculator,FAMILY,-0.301746,-0.166029,-0.866106,-0.175672,Free,0.0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
6870,1.700166,Sya9a Maroc - FR,FAMILY,0.610660,-0.166012,1.280615,-0.175578,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
6871,1.700487,Fr. Mike Schmitz Audio Teachings,FAMILY,1.523066,-0.166030,-0.823513,-0.175680,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
6872,1.701449,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,0.610660,0.053995,-0.167570,0.032361,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### 5. 🔠 Encoding Categorical Data
**Concept:** Models need numbers, not text like "Business" or "Teen".

**Method A: Pandas `get_dummies` (Simple)**

In [10]:
#get_dummies
import pandas as pd

cat_cols = df.select_dtypes(include = ['object']).columns.tolist()

# Convert all categorical columns into dummy/indicator variables
df_encoded = pd.get_dummies(df,columns=cat_cols, drop_first=True)

# Show encoded dataset
df_encoded.head()

,Unnamed: 0,Rating,Reviews,Size,Installs,Price,App_- Free Comics - Comic Apps,App_.R,App_/u/app,App_058.ba,...,Android Ver_5.0 - 6.0,Android Ver_5.0 - 8.0,Android Ver_5.0 and up,Android Ver_5.1 and up,Android Ver_6.0 and up,Android Ver_7.0 - 7.1.1,Android Ver_7.0 and up,Android Ver_7.1 and up,Android Ver_8.0 and up,Android Ver_Varies with device
0,-1.774912,-0.119265,-0.165945,-0.167570,-0.175474,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,-1.774592,-0.484227,-0.165498,-0.380538,-0.165280,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,-1.774271,0.975623,-0.117691,-0.606285,-0.071661,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,-1.773950,0.610660,-0.046909,0.087992,0.864532,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,-1.773629,0.245698,-0.165498,-0.857587,-0.173602,0.0,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

**Method B: Sklearn `OneHotEncoder` (Professional)**

In [16]:
#OneHotEncoder
#fit_transforminsurance_fraud_data.csv")
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Load the dataset
df = pd.read_csv("googleplaystore_cleaned.csv")

# Select categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
print("Categorical Columns:", cat_cols)

# Create OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform categorical columns
encoded_data = ohe.fit_transform(df[cat_cols])

# Convert to DataFrame
encoded_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out(cat_cols))

# Drop original categorical columns
df = df.drop(columns=cat_cols)

# Add encoded columns
df = pd.concat([df, encoded_df], axis=1)

# Final encoded dataset
df.head()

Categorical Columns: Index(['App', 'Category', 'Type', 'Content Rating', 'Genres', 'Last Updated',
       'Current Ver', 'Android Ver'],
      dtype='object')

,Unnamed: 0,Rating,Reviews,Size,Installs,Price,App_+Download 4 Instagram Twitter,App_- Free Comics - Comic Apps,App_.R,App_/u/app,...,Android Ver_5.0 - 6.0,Android Ver_5.0 - 8.0,Android Ver_5.0 and up,Android Ver_5.1 and up,Android Ver_6.0 and up,Android Ver_7.0 - 7.1.1,Android Ver_7.0 and up,Android Ver_7.1 and up,Android Ver_8.0 and up,Android Ver_Varies with device
0,0,4.1,-0.165945,19000000.0,10000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,3.9,-0.165498,14000000.0,500000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,4.7,-0.117691,8700000.0,5000000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,4.5,-0.046909,25000000.0,50000000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4.3,-0.165498,2800000.0,100000.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 6. 🚀 The Full Pipeline: ColumnTransformer
**Concept:** Instead of doing steps 4 and 5 manually, we wrap them in one object.

**Task:** Create a `ColumnTransformer` that Scales numerical data AND Encodes categorical data at the same time.

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [13]:
# Create ColumnTransformer

In [22]:
from sklearn.pipeline import Pipeline

In [23]:
numeric_features = ['Reviews', 'Size', 'Installs', 'Price']
categorical_features = ['Category', 'Content Rating']

In [24]:
# Create ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ]
)

In [25]:
from sklearn.pipeline import Pipeline
pipeline=Pipeline(steps=[('preprocessor',preprocessor)])

In [26]:
from sklearn import set_config
set_config(display='diagram')
pipeline

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Reviews', 'Size',
                                                   'Installs', 'Price']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Category',
                                                   'Content Rating'])]))])

In [ ]:
# In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
# On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [28]:
X=df[numeric_features+categorical_features]
X_preprocessed=pipeline.fit_transform(X)
print(f"Original Shape: {X_preprocessed.shape}")
print(f"Original Shape: {X.shape}")

KeyError: "['Category', 'Content Rating'] not in index"

In [29]:
new_columns=pipeline.named_steps['preprocessor'].get_feature_names_out()
df_preprocessed=pd.DataFrame(X_preprocessed.toarray(),columns=new_columns)
df_preprocessed.head()

NotFittedError: This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [21]:
# Create ColumnTransformer

# ------------------------------------------
# 1. Identify Numerical and Categorical Columns
# ------------------------------------------

# Numerical = int and float columns (e.g., Installs, Rating, Reviews, Size)
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Categorical = object (text) columns (e.g., Category, Type, Content Rating)
cat_cols = df.select_dtypes(include=['object']).columns.tolist()

# ------------------------------------------
# 2. Create ColumnTransformer
# ------------------------------------------
# This object performs BOTH scaling + encoding together

preprocessor = ColumnTransformer(
    transformers=[
        # Scale all numeric columns
        ('num', StandardScaler(), num_cols),

        # Encode all categorical columns
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)
    ]
)

# ------------------------------------------
# 3. Apply the transformations
# ------------------------------------------
# fit_transform() learns from the data AND applies transformations

processed_data = preprocessor.fit_transform(df)

# ------------------------------------------
# 4. Convert to DataFrame (optional but helpful)
# ------------------------------------------

# Get encoded categorical feature names
cat_features = preprocessor.named_transformers_['cat'].get_feature_names_out(cat_cols)

# Combine numeric + categorical column names
final_columns = list(num_cols) + list(cat_features)

# Build the final DataFrame
df_processed = pd.DataFrame(processed_data, columns=final_columns)

# Show first 5 rows
df_processed.head()

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.